controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
create_user:
    path: /create
    controller: App\Controller\UsersController::create
edit_user:
    path: /edit/{id}
    controller: App\Controller\UsersController::edit
    requirements:
        id: \d+
delete_user:
    path: /delete/{id}
    controller: App\Controller\UsersController::delete
    requirements:
        id: \d+