version: '3.3'
# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.23
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php/
    working_dir: /var/www/php
    container_name: php
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./php:/var/www/php
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

# Más info en
# https://tech.osteel.med/posts/docker-for-local-web-development-part-1-a-basic-lemp-stack

# Lanzar con
# docker-compose up -d

# Ver los logs con
# docker-compose logs -f